# Generated by Django 3.1.4 on 2021-01-03 02:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(upload_to='user_cards')),
                ('card_code', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=200)),
                ('user_company', models.CharField(blank=True, max_length=200)),
                ('user_title', models.CharField(blank=True, max_length=200)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user_email', models.EmailField(max_length=200)),
            ],
        ),
    ]
